export const cit = [
  "Achalpur",
  "Achhnera",
  "Adalaj",
  "Adilabad",
  "Adityapur",
  "Adoni",
  "Adoor",
  "Adra",
  "Adyar",
  "Afzalpur",
  "Agartala",
  "Agra",
  "Ahmedabad",
  "Ahmednagar",
  "Aizawl",
  "Ajmer",
  "Akola",
  "Akot",
  "Alappuzha",
  "Aligarh",
  "AlipurdUrban Agglomerationr",
  "Alirajpur",
  "Allahabad",
  "Alwar",
  "Amalapuram",
  "Amalner",
  "Ambejogai",
  "Ambikapur",
  "Amravati",
  "Amreli",
  "Amritsar",
  "Amroha",
  "Anakapalle",
  "Anand",
  "Anantapur",
  "Anantnag",
  "Anjangaon",
  "Anjar",
  "Ankleshwar",
  "Arakkonam",
  "Arambagh",
  "Araria",
  "Arrah",
  "Arsikere",
  "Aruppukkottai",
  "Arvi",
  "Arwal",
  "Asansol",
  "Asarganj",
  "Ashok Nagar",
  "Athni",
  "Attingal",
  "Aurangabad",
  "Aurangabad",
  "Azamgarh",
  "Bagaha",
  "Bageshwar",
  "Bahadurgarh",
  "Baharampur",
  "Bahraich",
  "Balaghat",
  "Balangir",
  "Baleshwar Town",
  "Ballari",
  "Balurghat",
  "Bankura",
  "Bapatla",
  "Baramula",
  "Barbil",
  "Bargarh",
  "Barh",
  "Baripada Town",
  "Barmer",
  "Barnala",
  "Barpeta",
  "Batala",
  "Bathinda",
  "Begusarai",
  "Belagavi",
  "Bellampalle",
  "Belonia",
  "Bengaluru",
  "Bettiah",
  "BhabUrban Agglomeration",
  "Bhadrachalam",
  "Bhadrak",
  "Bhagalpur",
  "Bhainsa",
  "Bharatpur",
  "Bharuch",
  "Bhatapara",
  "Bhavnagar",
  "Bhawanipatna",
  "Bheemunipatnam",
  "Bhilai Nagar",
  "Bhilwara",
  "Bhimavaram",
  "Bhiwandi",
  "Bhiwani",
  "Bhongir",
  "Bhopal",
  "Bhubaneswar",
  "Bhuj",
  "Bikaner",
  "Bilaspur",
  "Bobbili",
  "Bodhan",
  "Bokaro Steel City",
  "Bongaigaon City",
  "Brahmapur",
  "Buxar",
  "Byasanagar",
  "Chaibasa",
  "Chalakudy",
  "Chandausi",
  "Chandigarh",
  "Changanassery",
  "Charkhi Dadri",
  "Chatra",
  "Chennai",
  "Cherthala",
  "Chhapra",
  "Chhapra",
  "Chikkamagaluru",
  "Chilakaluripet",
  "Chirala",
  "Chirkunda",
  "Chirmiri",
  "Chittoor",
  "Chittur-Thathamangalam",
  "Coimbatore",
  "Cuttack",
  "Dalli-Rajhara",
  "Darbhanga",
  "Darjiling",
  "Davanagere",
  "Deesa",
  "Dehradun",
  "Dehri-on-Sone",
  "Delhi",
  "Deoghar",
  "Dhamtari",
  "Dhanbad",
  "Dharmanagar",
  "Dharmavaram",
  "Dhenkanal",
  "Dhoraji",
  "Dhubri",
  "Dhule",
  "Dhuri",
  "Dibrugarh",
  "Dimapur",
  "Diphu",
  "Dumka",
  "Dumraon",
  "Durg",
  "Eluru",
  "English Bazar",
  "Erode",
  "Etawah",
  "Faridabad",
  "Faridkot",
  "Farooqnagar",
  "Fatehabad",
  "Fatehpur Sikri",
  "Fazilka",
  "Firozabad",
  "Firozpur Cantt.",
  "Firozpur",
  "Forbesganj",
  "Gadwal",
  "Gandhinagar",
  "Gangarampur",
  "Ganjbasoda",
  "Gaya",
  "Giridih",
  "Goalpara",
  "Gobichettipalayam",
  "Gobindgarh",
  "Godhra",
  "Gohana",
  "Gokak",
  "Gooty",
  "Gopalganj",
  "Gudivada",
  "Gudur",
  "Gumia",
  "Guntakal",
  "Guntur",
  "Gurdaspur",
  "Gurgaon",
  "Guruvayoor",
  "Guwahati",
  "Gwalior",
  "Habra",
  "Hajipur",
  "Haldwani-cum-Kathgodam",
  "Hansi",
  "Hapur",
  "Hardoi ",
  "Hardwar",
  "Hazaribag",
  "Hindupur",
  "Hisar",
  "Hoshiarpur",
  "Hubli-Dharwad",
  "Hugli-Chinsurah",
  "Hyderabad",
  "Ichalkaranji",
  "Imphal",
  "Indore",
  "Itarsi",
  "Jabalpur",
  "Jagdalpur",
  "Jaggaiahpet",
  "Jagraon",
  "Jagtial",
  "Jaipur",
  "Jalandhar Cantt.",
  "Jalandhar",
  "Jalpaiguri",
  "Jamalpur",
  "Jammalamadugu",
  "Jammu",
  "Jamnagar",
  "Jamshedpur",
  "Jamui",
  "Jangaon",
  "Jatani",
  "Jehanabad",
  "Jhansi",
  "Jhargram",
  "Jharsuguda",
  "Jhumri Tilaiya",
  "Jind",
  "Jodhpur",
  "Jorhat",
  "Kadapa",
  "Kadi",
  "Kadiri",
  "Kagaznagar",
  "Kailasahar",
  "Kaithal",
  "Kakinada",
  "Kalimpong",
  "Kalpi",
  "Kalyan-Dombivali",
  "Kamareddy",
  "Kancheepuram",
  "Kandukur",
  "Kanhangad",
  "Kannur",
  "Kanpur",
  "Kapadvanj",
  "Kapurthala",
  "Karaikal",
  "Karimganj",
  "Karimnagar",
  "Karjat",
  "Karnal",
  "Karur",
  "Karwar",
  "Kasaragod",
  "Kashipur",
  "KathUrban Agglomeration",
  "Katihar",
  "Kavali",
  "Kayamkulam",
  "Kendrapara",
  "Kendujhar",
  "Keshod",
  "Khair",
  "Khambhat",
  "Khammam",
  "Khanna",
  "Kharagpur",
  "Kharar",
  "Khowai",
  "Kishanganj",
  "Kochi",
  "Kodungallur",
  "Kohima",
  "Kolar",
  "Kolkata",
  "Kollam",
  "Koratla",
  "Korba",
  "Kot Kapura",
  "Kota",
  "Kothagudem",
  "Kottayam",
  "Kovvur",
  "Koyilandy",
  "Kozhikode",
  "Kunnamkulam",
  "Kurnool",
  "Kyathampalle",
  "Lachhmangarh",
  "Ladnu",
  "Ladwa",
  "Lahar",
  "Laharpur",
  "Lakheri",
  "Lakhimpur",
  "Lakhisarai",
  "Lakshmeshwar",
  "Lal Gopalganj Nindaura",
  "Lalganj",
  "Lalganj",
  "Lalgudi",
  "Lalitpur",
  "Lalsot",
  "Lanka",
  "Lar",
  "Lathi",
  "Latur",
  "Lilong",
  "Limbdi",
  "Lingsugur",
  "Loha",
  "Lohardaga",
  "Lonar",
  "Lonavla",
  "Longowal",
  "Loni",
  "Losal",
  "Lucknow",
  "Ludhiana",
  "Lumding",
  "Lunawada",
  "Lunglei",
  "Macherla",
  "Machilipatnam",
  "Madanapalle",
  "Maddur",
  "Madhepura",
  "Madhubani",
  "Madhugiri",
  "Madhupur",
  "Madikeri",
  "Madurai",
  "Magadi",
  "Mahad",
  "Mahalingapura",
  "Maharajganj",
  "Maharajpur",
  "Mahasamund",
  "Mahbubnagar",
  "Mahe",
  "Mahemdabad",
  "Mahendragarh",
  "Mahesana",
  "Mahidpur",
  "Mahnar Bazar",
  "Mahuva",
  "Maihar",
  "Mainaguri",
  "Makhdumpur",
  "Makrana",
  "Malaj Khand",
  "Malappuram",
  "Malavalli",
  "Malda",
  "Malegaon",
  "Malerkotla",
  "Malkangiri",
  "Malkapur",
  "Malout",
  "Malpura",
  "Malur",
  "Manachanallur",
  "Manasa",
  "Manavadar",
  "Manawar",
  "Mancherial",
  "Mandalgarh",
  "Mandamarri",
  "Mandapeta",
  "Mandawa",
  "Mandi Dabwali",
  "Mandi",
  "Mandideep",
  "Mandla",
  "Mandsaur",
  "Mandvi",
  "Mandya",
  "Manendragarh",
  "Maner",
  "Mangaldoi",
  "Mangaluru",
  "Mangalvedhe",
  "Manglaur",
  "Mangrol",
  "Mangrol",
  "Mangrulpir",
  "Manihari",
  "Manjlegaon",
  "Mankachar",
  "Manmad",
  "Mansa",
  "Mansa",
  "Manuguru",
  "Manvi",
  "Manwath",
  "Mapusa",
  "Margao",
  "Margherita",
  "Marhaura",
  "Mariani",
  "Marigaon",
  "Markapur",
  "Marmagao",
  "Masaurhi",
  "Mathabhanga",
  "Mathura",
  "Mattannur",
  "Mauganj",
  "Mavelikkara",
  "Mavoor",
  "Mayang Imphal",
  "Medak",
  "Medininagar (Daltonganj)",
  "Medinipur",
  "Meerut",
  "Mehkar",
  "Memari",
  "Merta City",
  "Mhaswad",
  "Mhow Cantonment",
  "Mhowgaon",
  "Mihijam",
  "Mira-Bhayandar",
  "Mirganj",
  "Miryalaguda",
  "Modasa",
  "Modinagar",
  "Moga",
  "Mohali",
  "Mokameh",
  "Mokokchung",
  "Monoharpur",
  "Moradabad",
  "Morena",
  "Morinda, India",
  "Morshi",
  "Morvi",
  "Motihari",
  "Motipur",
  "Mount Abu",
  "Mudabidri",
  "Mudalagi",
  "Muddebihal",
  "Mudhol",
  "Mukerian",
  "Mukhed",
  "Muktsar",
  "Mul",
  "Mulbagal",
  "Multai",
  "Mumbai",
  "Mundargi",
  "Mundi",
  "Mungeli",
  "Munger",
  "Murliganj",
  "Murshidabad",
  "Murtijapur",
  "Murwara (Katni)",
  "Musabani",
  "Mussoorie",
  "Muvattupuzha",
  "Muzaffarpur",
  "Mysore",
  "Nabadwip",
  "Nabarangapur",
  "Nabha",
  "Nadbai",
  "Nadiad",
  "Nagaon",
  "Nagapattinam",
  "Nagar",
  "Nagari",
  "Nagarkurnool",
  "Nagaur",
  "Nagda",
  "Nagercoil",
  "Nagina",
  "Nagla",
  "Nagpur",
  "Nahan",
  "Naharlagun",
  "Naidupet",
  "Naihati",
  "Naila Janjgir",
  "Nainital",
  "Nainpur",
  "Najibabad",
  "Nakodar",
  "Nakur",
  "Nalbari",
  "Namagiripettai",
  "Namakkal",
  "Nanded-Waghala",
  "Nandgaon",
  "Nandivaram-Guduvancheri",
  "Nandura",
  "Nandurbar",
  "Nandyal",
  "Nangal",
  "Nanjangud",
  "Nanjikottai",
  "Nanpara",
  "Narasapuram",
  "Narasaraopet",
  "Naraura",
  "Narayanpet",
  "Nargund",
  "Narkatiaganj",
  "Narkhed",
  "Narnaul",
  "Narsinghgarh",
  "Narsinghgarh",
  "Narsipatnam",
  "Narwana",
  "Nashik",
  "Nasirabad",
  "Natham",
  "Nathdwara",
  "Naugachhia",
  "Naugawan Sadat",
  "Nautanwa",
  "Navalgund",
  "Navsari",
  "Nawabganj",
  "Nawada",
  "Nawanshahr",
  "Nawapur",
  "Nedumangad",
  "Neem-Ka-Thana",
  "Neemuch",
  "Nehtaur",
  "Nelamangala",
  "Nellikuppam",
  "Nellore",
  "Nepanagar",
  "New Delhi",
  "Neyveli (TS)",
  "Neyyattinkara",
  "Nidadavole",
  "Nilambur",
  "Nilanga",
  "Nimbahera",
  "Nirmal",
  "Niwai",
  "Niwari",
  "Nizamabad",
  "Nohar",
  "Noida",
  "Nokha",
  "Nokha",
  "Nongstoin",
  "Noorpur",
  "North Lakhimpur",
  "Nowgong",
  "Nowrozabad (Khodargama)",
  "Nuzvid",
  "O' Valley",
  "Obra",
  "Oddanchatram",
  "Ongole",
  "Orai",
  "Osmanabad",
  "Ottappalam",
  "Ozar",
  "P.N.Patti",
  "Pachora",
  "Pachore",
  "Pacode",
  "Padmanabhapuram",
  "Padra",
  "Padrauna",
  "Paithan",
  "Pakaur",
  "Palacole",
  "Palai",
  "Palakkad",
  "Palampur",
  "Palani",
  "Palanpur",
  "Palasa Kasibugga",
  "Palghar",
  "Pali",
  "Pali",
  "Palia Kalan",
  "Palitana",
  "Palladam",
  "Pallapatti",
  "Pallikonda",
  "Palwal",
  "Palwancha",
  "Panagar",
  "Panagudi",
  "Panaji",
  "Panamattom",
  "Panchkula",
  "Panchla",
  "Pandharkaoda",
  "Pandharpur",
  "Pandhurna",
  "PandUrban Agglomeration",
  "Panipat",
  "Panna",
  "Panniyannur",
  "Panruti",
  "Panvel",
  "Pappinisseri",
  "Paradip",
  "Paramakudi",
  "Parangipettai",
  "Parasi",
  "Paravoor",
  "Parbhani",
  "Pardi",
  "Parlakhemundi",
  "Parli",
  "Partur",
  "Parvathipuram",
  "Pasan",
  "Paschim Punropara",
  "Pasighat",
  "Patan",
  "Pathanamthitta",
  "Pathankot",
  "Pathardi",
  "Pathri",
  "Patiala",
  "Patna",
  "Patratu",
  "Pattamundai",
  "Patti",
  "Pattran",
  "Pattukkottai",
  "Patur",
  "Pauni",
  "Pauri",
  "Pavagada",
  "Pedana",
  "Peddapuram",
  "Pehowa",
  "Pen",
  "Perambalur",
  "Peravurani",
  "Peringathur",
  "Perinthalmanna",
  "Periyakulam",
  "Periyasemur",
  "Pernampattu",
  "Perumbavoor",
  "Petlad",
  "Phagwara",
  "Phalodi",
  "Phaltan",
  "Phillaur",
  "Phulabani",
  "Phulera",
  "Phulpur",
  "Phusro",
  "Pihani",
  "Pilani",
  "Pilibanga",
  "Pilibhit",
  "Pilkhuwa",
  "Pindwara",
  "Pinjore",
  "Pipar City",
  "Pipariya",
  "Piriyapatna",
  "Piro",
  "Pithampur",
  "Pithapuram",
  "Pithoragarh",
  "Pollachi",
  "Polur",
  "Pondicherry",
  "Ponnani",
  "Ponneri",
  "Ponnur",
  "Porbandar",
  "Porsa",
  "Port Blair",
  "Powayan",
  "Prantij",
  "Pratapgarh",
  "Pratapgarh",
  "Prithvipur",
  "Proddatur",
  "Pudukkottai",
  "Pudupattinam",
  "Pukhrayan",
  "Pulgaon",
  "Puliyankudi",
  "Punalur",
  "Punch",
  "Pune",
  "Punganur",
  "Punjaipugalur",
  "Puranpur",
  "Puri",
  "Purna",
  "Purnia",
  "PurqUrban Agglomerationzi",
  "Purulia",
  "Purwa",
  "Pusad",
  "Puthuppally",
  "Puttur",
  "Puttur",
  "Qadian",
  "Raayachuru",
  "Rabkavi Banhatti",
  "Radhanpur",
  "Rae Bareli",
  "Rafiganj",
  "Raghogarh-Vijaypur",
  "Raghunathganj",
  "Raghunathpur",
  "Rahatgarh",
  "Rahuri",
  "Raiganj",
  "Raigarh",
  "Raikot",
  "Raipur",
  "Rairangpur",
  "Raisen",
  "Raisinghnagar",
  "Rajagangapur",
  "Rajahmundry",
  "Rajakhera",
  "Rajaldesar",
  "Rajam",
  "Rajampet",
  "Rajapalayam",
  "Rajauri",
  "Rajgarh (Alwar)",
  "Rajgarh (Churu)",
  "Rajgarh",
  "Rajgir",
  "Rajkot",
  "Rajnandgaon",
  "Rajpipla",
  "Rajpura",
  "Rajsamand",
  "Rajula",
  "Rajura",
  "Ramachandrapuram",
  "Ramagundam",
  "Ramanagaram",
  "Ramanathapuram",
  "Ramdurg",
  "Rameshwaram",
  "Ramganj Mandi",
  "Ramgarh",
  "Ramnagar",
  "Ramnagar",
  "Ramngarh",
  "Rampur Maniharan",
  "Rampur",
  "Rampura Phul",
  "Rampurhat",
  "Ramtek",
  "Ranaghat",
  "Ranavav",
  "Ranchi",
  "Ranebennuru",
  "Rangia",
  "Rania",
  "Ranibennur",
  "Ranipet",
  "Rapar",
  "Rasipuram",
  "Rasra",
  "Ratangarh",
  "Rath",
  "Ratia",
  "Ratlam",
  "Ratnagiri",
  "Rau",
  "Raurkela",
  "Raver",
  "Rawatbhata",
  "Rawatsar",
  "Raxaul Bazar",
  "Rayachoti",
  "Rayadurg",
  "Rayagada",
  "Reengus",
  "Rehli",
  "Renigunta",
  "Renukoot",
  "Reoti",
  "Repalle",
  "Revelganj",
  "Rewa",
  "Rewari",
  "Rishikesh",
  "Risod",
  "Robertsganj",
  "Robertson Pet",
  "Rohtak",
  "Ron",
  "Roorkee",
  "Rosera",
  "Rudauli",
  "Rudrapur",
  "Rudrapur",
  "Rupnagar",
  "Sabalgarh",
  "Sadabad",
  "Sadalagi",
  "Sadasivpet",
  "Sadri",
  "Sadulpur",
  "Sadulshahar",
  "Safidon",
  "Safipur",
  "Sagar",
  "Sagara",
  "Sagwara",
  "Saharanpur",
  "Saharsa",
  "Sahaspur",
  "Sahaswan",
  "Sahawar",
  "Sahibganj",
  "Sahjanwa",
  "Saidpur",
  "Saiha",
  "Sailu",
  "Sainthia",
  "Sakaleshapura",
  "Sakti",
  "Salaya",
  "Salem",
  "Salur",
  "Samalkha",
  "Samalkot",
  "Samana",
  "Samastipur",
  "Sambalpur",
  "Sambhal",
  "Sambhar",
  "Samdhan",
  "Samthar",
  "Sanand",
  "Sanawad",
  "Sanchore",
  "Sandi",
  "Sandila",
  "Sanduru",
  "Sangamner",
  "Sangareddy",
  "Sangaria",
  "Sangli",
  "Sangole",
  "Sangrur",
  "Sankarankovil",
  "Sankari",
  "Sankeshwara",
  "Santipur",
  "Sarangpur",
  "Sardarshahar",
  "Sardhana",
  "Sarni",
  "Sarsod",
  "Sasaram",
  "Sasvad",
  "Satana",
  "Satara",
  "Sathyamangalam",
  "Satna",
  "Sattenapalle",
  "Sattur",
  "Saunda",
  "Saundatti-Yellamma",
  "Sausar",
  "Savanur",
  "Savarkundla",
  "Savner",
  "Sawai Madhopur",
  "Sawantwadi",
  "Sedam",
  "Sehore",
  "Sendhwa",
  "Seohara",
  "Seoni",
  "Seoni-Malwa",
  "Shahabad",
  "Shahabad, Hardoi",
  "Shahabad, Rampur",
  "Shahade",
  "Shahbad",
  "Shahdol",
  "Shahganj",
  "Shahjahanpur",
  "Shahpur",
  "Shahpura",
  "Shahpura",
  "Shajapur",
  "Shamgarh",
  "Shamli",
  "Shamsabad, Agra",
  "Shamsabad, Farrukhabad",
  "Shegaon",
  "Sheikhpura",
  "Shendurjana",
  "Shenkottai",
  "Sheoganj",
  "Sheohar",
  "Sheopur",
  "Sherghati",
  "Sherkot",
  "Shiggaon",
  "Shikaripur",
  "Shikarpur, Bulandshahr",
  "Shikohabad",
  "Shillong",
  "Shimla",
  "Shirdi",
  "Shirpur-Warwade",
  "Shirur",
  "Shishgarh",
  "Shivamogga",
  "Shivpuri",
  "Sholavandan",
  "Sholingur",
  "Shoranur",
  "Shrigonda",
  "Shrirampur",
  "Shrirangapattana",
  "Shujalpur",
  "Siana",
  "Sibsagar",
  "Siddipet",
  "Sidhi",
  "Sidhpur",
  "Sidlaghatta",
  "Sihor",
  "Sihora",
  "Sikanderpur",
  "Sikandra Rao",
  "Sikandrabad",
  "Sikar",
  "Silao",
  "Silapathar",
  "Silchar",
  "Siliguri",
  "Sillod",
  "Silvassa",
  "Simdega",
  "Sindagi",
  "Sindhagi",
  "Sindhnur",
  "Singrauli",
  "Sinnar",
  "Sira",
  "Sircilla",
  "Sirhind Fatehgarh Sahib",
  "Sirkali",
  "Sirohi",
  "Sironj",
  "Sirsa",
  "Sirsaganj",
  "Sirsi",
  "Sirsi",
  "Siruguppa",
  "Sitamarhi",
  "Sitapur",
  "Sitarganj",
  "Sivaganga",
  "Sivagiri",
  "Sivakasi",
  "Siwan",
  "Sohagpur",
  "Sohna",
  "Sojat",
  "Solan",
  "Solapur",
  "Sonamukhi",
  "Sonepur",
  "Songadh",
  "Sonipat",
  "Sopore",
  "Soro",
  "Soron",
  "Soyagaon",
  "Sri Madhopur",
  "Srikakulam",
  "Srikalahasti",
  "Srinagar",
  "Srinagar",
  "Srinivaspur",
  "Srirampore",
  "Srisailam Project (Right Flank Colony) Township",
  "Srivilliputhur",
  "Sugauli",
  "Sujangarh",
  "Sujanpur",
  "Sullurpeta",
  "Sultanganj",
  "Sultanpur",
  "Sumerpur",
  "Sumerpur",
  "Sunabeda",
  "Sunam",
  "Sundargarh",
  "Sundarnagar",
  "Supaul",
  "Surandai",
  "Surapura",
  "Surat",
  "Suratgarh",
  "SUrban Agglomerationr",
  "Suri",
  "Suriyampalayam",
  "Suryapet",
  "Tadepalligudem",
  "Tadpatri",
  "Takhatgarh",
  "Taki",
  "Talaja",
  "Talcher",
  "Talegaon Dabhade",
  "Talikota",
  "Taliparamba",
  "Talode",
  "Talwara",
  "Tamluk",
  "Tanda",
  "Tandur",
  "Tanuku",
  "Tarakeswar",
  "Tarana",
  "Taranagar",
  "Taraori",
  "Tarbha",
  "Tarikere",
  "Tarn Taran",
  "Tasgaon",
  "Tehri",
  "Tekkalakote",
  "Tenali",
  "Tenkasi",
  "Tenu dam-cum-Kathhara",
  "Terdal",
  "Tezpur",
  "Thakurdwara",
  "Thammampatti",
  "Thana Bhawan",
  "Thane",
  "Thanesar",
  "Thangadh",
  "Thanjavur",
  "Tharad",
  "Tharamangalam",
  "Tharangambadi",
  "Theni Allinagaram",
  "Thirumangalam",
  "Thirupuvanam",
  "Thiruthuraipoondi",
  "Thiruvalla",
  "Thiruvallur",
  "Thiruvananthapuram",
  "Thiruvarur",
  "Thodupuzha",
  "Thoubal",
  "Thrissur",
  "Thuraiyur",
  "Tikamgarh",
  "Tilda Newra",
  "Tilhar",
  "Tindivanam",
  "Tinsukia",
  "Tiptur",
  "Tirora",
  "Tiruchendur",
  "Tiruchengode",
  "Tiruchirappalli",
  "Tirukalukundram",
  "Tirukkoyilur",
  "Tirunelveli",
  "Tirupathur",
  "Tirupathur",
  "Tirupati",
  "Tiruppur",
  "Tirur",
  "Tiruttani",
  "Tiruvannamalai",
  "Tiruvethipuram",
  "Tiruvuru",
  "Tirwaganj",
  "Titlagarh",
  "Tittakudi",
  "Todabhim",
  "Todaraisingh",
  "Tohana",
  "Tonk",
  "Tuensang",
  "Tuljapur",
  "Tulsipur",
  "Tumkur",
  "Tumsar",
  "Tundla",
  "Tuni",
  "Tura",
  "Uchgaon",
  "Udaipur",
  "Udaipur",
  "Udaipurwati",
  "Udgir",
  "Udhagamandalam",
  "Udhampur",
  "Udumalaipettai",
  "Udupi",
  "Ujhani",
  "Ujjain",
  "Umarga",
  "Umaria",
  "Umarkhed",
  "Umbergaon",
  "Umred",
  "Umreth",
  "Una",
  "Unjha",
  "Unnamalaikadai",
  "Unnao",
  "Upleta",
  "Uran Islampur",
  "Uran",
  "Uravakonda",
  "Urmar Tanda",
  "Usilampatti",
  "Uthamapalayam",
  "Uthiramerur",
  "Utraula",
  "Vadakkuvalliyur",
  "Vadalur",
  "Vadgaon Kasba",
  "Vadipatti",
  "Vadnagar",
  "Vadodara",
  "Vaijapur",
  "Vaikom",
  "Valparai",
  "Valsad",
  "Vandavasi",
  "Vaniyambadi",
  "Vapi",
  "Vapi",
  "Varanasi",
  "Varkala",
  "Vasai-Virar",
  "Vatakara",
  "Vedaranyam",
  "Vellakoil",
  "Vellore",
  "Venkatagiri",
  "Veraval",
  "Vidisha",
  "Vijainagar, Ajmer",
  "Vijapur",
  "Vijayapura",
  "Vijayawada",
  "Vijaypur",
  "Vikarabad",
  "Vikramasingapuram",
  "Viluppuram",
  "Vinukonda",
  "Viramgam",
  "Virudhachalam",
  "Virudhunagar",
  "Visakhapatnam",
  "Visnagar",
  "Viswanatham",
  "Vita",
  "Vizianagaram",
  "Vrindavan",
  "Vyara",
  "Wadgaon Road",
  "Wadhwan",
  "Wadi",
  "Wai",
  "Wanaparthy",
  "Wani",
  "Wankaner",
  "Wara Seoni",
  "Warangal",
  "Wardha",
  "Warhapur",
  "Warisaliganj",
  "Warora",
  "Warud",
  "Washim",
  "Wokha",
  "Yadgir",
  "Yamunanagar",
  "Yanam",
  "Yavatmal",
  "Yawal",
  "Yellandu",
  "Yemmiganur",
  "Yerraguntla",
  "Yevla",
  "Zaidpur",
  "Zamania",
  "Zira",
  "Zirakpur",
  "Zunheboto",
];

export const cas = [
  "Ad Dharmi",
  "Adi Andhra",
  "Adi-karnataka",
  "Agarwal",
  "Agnikula Kshatriya",
  "Agri",
  "Ahir Shimpi",
  "Ahom",
  "Ambalavasi",
  "Arekatica",
  "Arora",
  "Arunthathiyar",
  "Arya Vysya",
  "Ayyaraka",
  "Badaga",
  "Bagdi",
  "Baishnab",
  "Baishya",
  "Bajantri",
  "Balija",
  "Banayat Oriya",
  "Banik",
  "Baniya",
  "Baniya - Bania",
  "Baniya - Kumuti",
  "Banjara",
  "Barai",
  "Bari",
  "Baria",
  "Barujibi",
  "Besta",
  "Bhandari",
  "Bhatia",
  "Bhatraju",
  "Bhavasar Kshatriya",
  "Bhoi",
  "Bhovi",
  "Bhoyar",
  "Billava",
  "Bishnoi/Vishnoi",
  "Bondili",
  "Boyer",
  "Brahmbatt",
  "Brahmin",
  "Brahmin - Anavil",
  "Brahmin - Audichya",
  "Brahmin - Barendra",
  "Brahmin - Bhatt",
  "Brahmin - Bhumihar",
  "Brahmin - Daivadnya",
  "Brahmin - Danua",
  "Brahmin - Deshastha",
  "Brahmin - Dhiman",
  "Brahmin - Embrandiri",
  "Brahmin - Garhwali",
  "Brahmin - Gaur",
  "Brahmin - Goswami",
  "Brahmin - Gujar Gaur",
  "Brahmin - Gurukkal",
  "Brahmin - Halua",
  "Brahmin - Havyaka",
  "Brahmin - Hoysala",
  "Brahmin - Iyengar",
  "Brahmin - Iyer",
  "Brahmin - Jhadua",
  "Brahmin - Jyotish",
  "Brahmin - Kanyakubj",
  "Brahmin - Karhade",
  "Brahmin - Khandelwal",
  "Brahmin - Kokanastha",
  "Brahmin - Kota",
  "Brahmin - Kulin",
  "Brahmin - Kumoani",
  "Brahmin - Madhwa",
  "Brahmin - Maithil",
  "Brahmin - Modh",
  "Brahmin - Mohyal",
  "Brahmin - Nagar",
  "Brahmin - Namboodiri",
  "Brahmin - Narmadiya",
  "Brahmin - Niyogi",
  "Brahmin - Paliwal",
  "Brahmin - Panda",
  "Brahmin - Pandit",
  "Brahmin - Pareek",
  "Brahmin - Pushkarna",
  "Brahmin - Rarhi",
  "Brahmin - Rigvedi",
  "Brahmin - Rudraj",
  "Brahmin - Sakaldwipi",
  "Brahmin - Sanadya",
  "Brahmin - Sanketi",
  "Brahmin - Saraswat",
  "Brahmin - Saryuparin",
  "Brahmin - Shivhalli",
  "Brahmin - Shrimali",
  "Brahmin - Sikhwal",
  "Brahmin - Smartha",
  "Brahmin - Sri Vishnava",
  "Brahmin - Stanika",
  "Brahmin - Tyagi",
  "Brahmin - Vaikhanasa",
  "Brahmin - Velanadu",
  "Brahmin - Vyas",
  "Brajastha Maithil",
  "Brajastha Maithil",
  "Bunt (Shetty)",
  "CKP",
  "Chalawadi and Holeya",
  "Chambhar",
  "Chandravanshi Kahar",
  "Chasa",
  "Chattada Sri Vaishnava",
  "Chaudary",
  "Chaurasia",
  "Chennadasar",
  "Chettiar",
  "Chhetri",
  "Chippolu (Mera)",
  "Coorgi",
  "Devadiga",
  "Devandra Kula Vellalar",
  "Devang Koshthi",
  "Devanga",
  "Devrukhe Brahmin",
  "Dhangar",
  "Dheevara",
  "Dhiman",
  "Dhoba",
  "Dhobi",
  "Dhor / Kakkayya",
  "Dommala",
  "Dumal",
  "Dusadh (Paswan)",
  "Ediga",
  "Ezhava",
  "Ezhuthachan",
  "Gabit",
  "Ganda",
  "Gandla",
  "Ganiga",
  "Garhwali",
  "Gatti",
  "Gavara",
  "Gawali",
  "Ghisadi",
  "Ghumar",
  "Goala",
  "Goan",
  "Gomantak",
  "Gondhali",
  "Goud",
  "Gounder",
  "Gowda",
  "Gramani",
  "Gudia",
  "Gujjar",
  "Gupta",
  "Guptan",
  "Gurav",
  "Gurjar",
  "Halba Koshti",
  "Helava",
  "Hugar (Jeer)",
  "Intercaste",
  "Irani",
  "Jaalari",
  "Jaiswal",
  "Jandra",
  "Jangam",
  "Jangra - Brahmin",
  "Jat",
  "Jatav",
  "Jetty/Malla",
  "Jogi (Nath)",
  "Kachara",
  "Kadava Patel",
  "Kahar",
  "Kaibarta",
  "Kalal",
  "Kalanji",
  "Kalar",
  "Kalinga",
  "Kalinga Vysya",
  "Kalita",
  "Kalwar",
  "Kamboj",
  "Kamma",
  "Kansari",
  "Kapu",
  "Karana",
  "Karmakar",
  "Karuneegar",
  "Kasar",
  "Kashyap",
  "Katiya",
  "Kavuthiyya/Ezhavathy",
  "Kayastha",
  "Khandayat",
  "Khandelwal",
  "Kharwa",
  "Kharwar",
  "Khatri",
  "Kirar",
  "Kokanastha Maratha",
  "Koli",
  "Koli Mahadev",
  "Koli Patel",
  "Kongu Vellala Gounder",
  "Konkani",
  "Korama",
  "Kori",
  "Kosthi",
  "Krishnavaka",
  "Kshatriya",
  "Kudumbi",
  "Kulal",
  "Kulalar",
  "Kulita",
  "Kumawat",
  "Kumbhakar",
  "Kumbhar",
  "Kumhar",
  "Kummari",
  "Kunbi",
  "Kuravan",
  "Kurmi",
  "Kurmi Kshatriya",
  "Kuruba",
  "Kuruhina Shetty",
  "Kurumbar",
  "Kushwaha (Koiri)",
  "Kutchi",
  "Lambadi",
  "Leva patel",
  "Leva patil",
  "Lingayath",
  "Lodhi Rajput",
  "Lohana",
  "Lohar",
  "Loniya",
  "Lubana",
  "Madiga",
  "Mahajan",
  "Mahar",
  "Mahendra",
  "Maheshwari",
  "Mahishya",
  "Majabi",
  "Mala",
  "Mali",
  "Malla",
  "Malviya Brahmin",
  "Mangalorean",
  "Manipuri",
  "Mapila",
  "Maratha",
  "Maruthuvar",
  "Matang",
  "Mathur",
  "Maurya / Shakya",
  "Meena",
  "Meenavar",
  "Mehra",
  "Meru Darji",
  "Mochi",
  "Modak",
  "Mogaveera",
  "Mudaliyar",
  "Mudiraj",
  "Mukkulathor",
  "Munnuru Kapu",
  "Muthuraja",
  "Naagavamsam",
  "Nadar",
  "Nagaralu",
  "Nai",
  "Naicker",
  "Naik",
  "Nair",
  "Nambiar",
  "Namosudra",
  "Napit",
  "Nayaka",
  "Neeli",
  "Nepali",
  "Nhavi",
  "Oswal",
  "Otari",
  "Padmasali",
  "Pal",
  "Panchal",
  "Pandaram",
  "Panicker",
  "Parkava Kulam",
  "Parsi",
  "Partraj",
  "Pasi",
  "Patel",
  "Pathare Prabhu",
  "Patnaick",
  "Patra",
  "Perika",
  "Pillai",
  "Poosala",
  "Porwal",
  "Prajapati",
  "Raigar",
  "Rajaka",
  "Rajastani",
  "Rajbhar",
  "Rajbonshi",
  "Rajpurohit",
  "Rajput",
  "Ramanandi",
  "Ramdasia",
  "Ramgariah",
  "Ramoshi",
  "Rawat",
  "Reddy",
  "Relli",
  "Ror",
  "SC",
  "SKP",
  "ST",
  "Sadgope",
  "Saha",
  "Sahu",
  "Saini",
  "Saliya",
  "Sathwara",
  "Savji",
  "Senai Thalaivar",
  "Senguntha Mudaliyar",
  "Settibalija",
  "Shimpi",
  "Sindhi",
  "Sindhi-Amil",
  "Sindhi-Baibhand",
  "Sindhi-Bhanusali",
  "Sindhi-Bhatia",
  "Sindhi-Chhapru",
  "Sindhi-Dadu",
  "Sindhi-Hyderabadi",
  "Sindhi-Larai",
  "Sindhi-Larkana",
  "Sindhi-Lohana",
  "Sindhi-Rohiri",
  "Sindhi-Sahiti",
  "Sindhi-Sakkhar",
  "Sindhi-Sehwani",
  "Sindhi-Shikarpuri",
  "Sindhi-Thatai",
  "Sonar",
  "Soni",
  "Sourashtra",
  "Sozhiya Vellalar",
  "Srisayana",
  "Sugali (Naika)",
  "Sunari",
  "Sundhi",
  "Surya Balija",
  "Suthar",
  "Swakula Sali",
  "Tamboli",
  "Tanti",
  "Tantubai",
  "Telaga",
  "Teli",
  "Thakkar",
  "Thakore",
  "Thakur",
  "Thigala",
  "Thiyya",
  "Tili",
  "Togata",
  "Tonk Kshatriya",
  "Turupu Kapu",
  "Uppara",
  "Urali Gounder",
  "Urs",
  "Vada Balija",
  "Vaddera",
  "Vaish",
  "Vaishnav",
  "Vaishnava",
  "Vaishya",
  "Vaishya Vani",
  "Valluvan",
  "Valmiki",
  "Vania",
  "Vanika Vyshya",
  "Vaniya",
  "Vanjara",
  "Vanjari",
  "Vankar",
  "Vannar",
  "Vannia Kula Kshatriyar",
  "Variar",
  "Varshney",
  "Veera Saivam",
  "Velaan",
  "Velama",
  "Vellalar",
  "Veluthedathu Nair",
  "Vettuva Gounder",
  "Vilakkithala Nair",
  "Viswabrahmin",
  "Viswakarma",
  "Vokkaliga",
  "Vysya",
  "Yadav",
  "Yellapu",
  "Muslim - Ansari",
  "Muslim - Arain",
  "Muslim - Awan",
  "Alavi - Bohra",
  "Muslim - Dakhini",
  "Muslim - Dudekula",
  "Muslim - Hanafi",
  "Muslim - Jat",
  "Muslim - Khoja",
  "Muslim - Labbay",
  "Muslim - Malik",
  "Muslim - Mappila",
  "Muslim - Marakayar",
  "Muslim - Memon",
  "Muslim - Mughal",
  "Muslim - Pathan",
  "Muslim - Qureshi",
  "Muslim - Rajput",
  "Muslim - Rowther",
  "Muslim - Shafi",
  "Muslim - Sheikh",
  "Muslim - Syed",
  "Muslim - UnSpecified",
  "Shia Isma'ilis (Seveners)",
  "Shia Ithna Asharis (Twelvers)",
  "Muslim - Ansari",
  "Muslim - Arain",
  "Muslim - Awan",
  "Alavi - Bohra",
  "Muslim - Dakhini",
  "Muslim - Dudekula",
  "Muslim - Hanafi",
  "Muslim - Jat",
  "Muslim - Khoja",
  "Muslim - Labbay",
  "Muslim - Malik",
  "Muslim - Mappila",
  "Muslim - Marakayar",
  "Muslim - Memon",
  "Muslim - Mughal",
  "Muslim - Pathan",
  "Muslim - Qureshi",
  "Muslim - Rajput",
  "Muslim - Rowther",
  "Muslim - Shafi",
  "Muslim - Sheikh",
  "Muslim - Syed",
  "Muslim - UnSpecified",
  "Sunni Hanabali",
  "Sunni Hanafi",
  "Sunni Maliki",
  "Sunni Shafii",
  "Muslim - Ansari",
  "Muslim - Arain",
  "Muslim - Awan",
  "Alavi - Bohra",
  "Muslim - Dakhini",
  "Muslim - Dudekula",
  "Muslim - Hanafi",
  "Muslim - Jat",
  "Muslim - Khoja",
  "Muslim - Labbay",
  "Muslim - Malik",
  "Muslim - Mappila",
  "Muslim - Marakayar",
  "Muslim - Memon",
  "Muslim - Mughal",
  "Muslim - Pathan",
  "Muslim - Qureshi",
  "Muslim - Rajput",
  "Muslim - Rowther",
  "Muslim - Shafi",
  "Muslim - Sheikh",
  "Muslim - Syed",
  "Muslim - UnSpecified",
  "Adventist",
  "Anglican / Episcopal",
  "Apostolic",
  "Assyrian",
  "Assembly of God (AG)",
  "Baptist",
  "Calvinist",
  "Christian - Born Again",
  "Christian - Bretheren",
  "Christian - Church of South India",
  "Christian - Evangelist",
  "Christian - Jacobite",
  "Christian - Knanaya",
  "Christian - Knanaya Catholic",
  "Christian - Knanaya Jacobite",
  "Christian - Latin Catholic",
  "Christian - Malankara",
  "Christian - Marthoma",
  "Christian - Pentacost",
  "Christian - Roman Catholic",
  "Christian - Syrian Catholic",
  "Christian - Syrian Jacobite",
  "Christian - Syrian Orthodox",
  "Christian - Syro Malabar",
  "Christian - Unspecified",
  "Church of God",
  "Church of Christ",
  "Church of North India",
  "Congregational",
  "East Indian Catholic",
  "Jehovah's Witnesses",
  "Latter day saints",
  "Lutheran",
  "Melkite",
  "Malabar Independent Syrian Church",
  "Mennonite",
  "Methodist",
  "Moravian",
  "Protestant",
  "Presbyterian",
  "Seventh-day Adventist",
  "Reformed Baptist",
  "Reformed Presbyterian",
  "Knanaya",
  "Knanaya Catholic",
  "Knanaya Jacobite",
  "St. Thomas Evangelical",
  "Syrian Jacobite",
  "Syrian Orthodox",
  "Sikh - Ahluwalia",
  "Sikh - Arora",
  "Sikh - Bhatia",
  "Sikh - Ghumar",
  "Sikh - Intercaste",
  "Sikh - Jat",
  "Sikh - Kamboj",
  "Sikh - Khatri",
  "Sikh - Kshatriya",
  "Sikh - Lubana",
  "Sikh - Majabi",
  "Sikh - Nai",
  "Sikh - No Bar",
  "Sikh - Rajput",
  "Sikh - Ramdasia",
  "Sikh - Ramgharia",
  "Sikh - Saini",
  "Sikh - Bhatra",
  "Sikh - Tonk Kshatriya",
  "Sikh - Unspecified",
  "Jain - Agarwal",
  "Jain - Bania",
  "Jain - Intercaste",
  "Jain - Jaiswal",
  "Jain - Khandelwal",
  "Jain - Kutchi",
  "Jain - No Bar",
  "Jain - Oswal",
  "Jain - Porwal",
  "Jain - Unspecified",
  "Jain - Vaishya",
  "Jain - KVO",
  "Digambar-Bisapanthi",
  "Digambar-Gumanapanthi",
  "Digambar-Taranapanthi",
  "Digambar-Terapanthi",
  "Digambar-Totapanthi",
  "Jain - Agarwal",
  "Jain - Bania",
  "Jain - Intercaste",
  "Jain - Jaiswal",
  "Jain - Khandelwal",
  "Jain - Kutchi",
  "Jain - No Bar",
  "Jain - Oswal",
  "Jain - Porwal",
  "Jain - Unspecified",
  "Jain - Vaishya",
  "Jain - KVO",
  "Shvetambar-Murtipujaka",
  "Shvetambar-Sthanakvasi",
  "Shvetambar-Terapanthi",
  "Jain - Agarwal",
  "Jain - Bania",
  "Jain - Intercaste",
  "Jain - Jaiswal",
  "Jain - Khandelwal",
  "Jain - Kutchi",
  "Jain - No Bar",
  "Jain - Oswal",
  "Jain - Porwal",
  "Jain - Unspecified",
  "Jain - Vaishya",
  "Jain - KVO",
  "Irani",
  "Parsi",
  "Intercaste",
  "Mahayana",
  "Nichiren Buddhism",
  "Pure Land Buddhism",
  "Tantrayana (Vajrayana Tibetan)",
  "Theravada (Hinayana)",
  "Tendai Buddhism (Japanese)",
  "Zen Buddhism (China)",
];
export const hei = [
  '4.0', '4.1', '4.2', '4.3', '4.4',' 4.5', '4.6',' 4.7', '4.8', '4.9', '5.0', '5.1', '5.2', '5.3', '5.4',
  '5.5', '5.6', '5.7', '5.8', '5.9', '6.0', '6.1', '6.2', '6.3', '6.4', '6.5',' 6.6', '6.7', '6.8', '6.9',
  '6.0', '7.0', '7.1',
];

export const rel = [
  "Hindu",
  "Muslim",
  "Christian",
  "Sikh",
  "Parsi",
  "Jain",
  "Buddhist",
  "Jewish",
  "No_Religion",
  "Spiritual",
  "Other",
];

export const tou = [
  "Hindi",
  "English",
  "Marathi",
  "Punjabi",
  "Bengali",
  "Gujarati",
  "Urdu",
  "Telugu",
  "Kannada",
  "English",
  "Tamil",
  "Oriya",
  "Marwari",
  "More",
  "Aka",
  "Arabic",
  "Arunachali",
  "Assamese",
  "Awadhi",
  "Baluchi",
  "Bengali",
  "Bhojpuri",
  "Bhutia",
  "Brahui",
  "Brij",
  "Burmese",
  "Chattis,garhi",
  "Chinese",
  "Coorgi",
  "Dogri",
  "English,",
  "French",
  "Garhwali,",
  "Garo",
  "Gujarati",
  "Haryana",
  "Himachal",
  "Pahari",
  "Hindi",
  "Hindko",
  "Kakbarak,",
  "Kanauji",
  "Kannada",
  "Kashmiri",
  "Khandesi",
  "Khasi",
  "Konkani,",
  "Koshali",
  "Kumaoni",
  "Kutchi",
  "Ladakhi",
  "Lepcha",
  "Magahi",
  "Maithili,",
  "Malay",
  "Malayal",
  "Manipuri",
  "Marathi",
  "Marwari",
  "Miji",
  "Mizo",
  "Monpa",
  "Nepali",
  "Odia",
  "Pashto",
  "Persian",
  "Punjabi",
  "Rajasthan",
  "Russian",
  "Sanskrit",
  "Santhali",
  "Seraiki",
  "Sindhi",
  "Sinhala",
  "Sourashtr",
  "Spanish",
  "Swedish",
  "Tagalog",
  "Tamil",
  "Telugu",
  "Tulu",
  "Urdu",
  "Other",
];

export const sta = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttarakhand",
  "Uttar Pradesh",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli",
  "Daman and Diu",
  "Delhi",
  "Lakshadweep",
  "Puducherry",
];
export const inc = ["No Income","Rs.0-1 Lakh","Rs.1-2 Lakh","Rs.2-3 Lakh",
"Rs.3-4 Lakh","Rs.4-5 Lakh","Rs.6-7 Lakh","Rs.7-8 Lakh","Rs.8-9 Lakh","Rs.9-10 Lakh",
"Rs.11-12 Lakh","Rs.12-13 Lakh"]

export const edu = ["B.E/B.TECH","B.PHARMA","B.E/M.TECH","M.PHARMA","MCA/PGDCA","BCA",
"BIT","MBA","BBA","BHM","MBBS","M.D","MABS","BHMS","BL/LLB","ML/LLM","B.A","B.SC","PH.D",
"M.PHIL","B.A","B.SC","M.A","M.SC","M.ED","MSW","BFA","MFA","BJMC","MJMC","PH.D","Other"]

export const mot = [
  "Hindi",
  "English",
  "Marathi",
  "Punjabi",
  "Bengali",
  "Gujarati",
  "Urdu",
  "Telugu",
  "Kannada",
  "English",
  "Tamil",
  "Oriya",
  "Marwari",
  "More",
  "Aka",
  "Arabic",
  "Arunachali",
  "Assamese",
  "Awadhi",
  "Baluchi",
  "Bengali",
  "Bhojpuri",
  "Bhutia",
  "Brahui",
  "Brij",
  "Burmese",
  "Chattis,garhi",
  "Chinese",
  "Coorgi",
  "Dogri",
  "English,",
  "French",
  "Garhwali,",
  "Garo",
  "Gujarati",
  "Haryana",
  "Himachal",
  "Pahari",
  "Hindi",
  "Hindko",
  "Kakbarak,",
  "Kanauji",
  "Kannada",
  "Kashmiri",
  "Khandesi",
  "Khasi",
  "Konkani,",
  "Koshali",
  "Kumaoni",
  "Kutchi",
  "Ladakhi",
  "Lepcha",
  "Magahi",
  "Maithili,",
  "Malay",
  "Malayal",
  "Manipuri",
  "Marathi",
  "Marwari",
  "Miji",
  "Mizo",
  "Monpa",
  "Nepali",
  "Odia",
  "Pashto",
  "Persian",
  "Punjabi",
  "Rajasthan",
  "Russian",
  "Sanskrit",
  "Santhali",
  "Seraiki",
  "Sindhi",
  "Sinhala",
  "Sourashtr",
  "Spanish",
  "Swedish",
  "Tagalog",
  "Tamil",
  "Telugu",
  "Tulu",
  "Urdu",
  "Other",
];

export const age = [
  "18",
  "19",
  "20",
  "21",
  "22",
  "23",
  "24",
  "25",
  "26",
  "27",
  "28",
  "29",
  "30",
  "31",
  "32",
  "33",
  "34",
  "35",
  "36",
  "37 ",
  "38",
  "39",
  "40",
  "41",
  "42",
  "43",
  "44",
  "45",
  "46",
  "47",
  "48",
  "49",
  "50",
  "51",
  "52",
  "53",
  "54",
  "55",
  "56",
  "57",
  "58",
  "59",
  "60",
  "61",
  "62",
  "63",
  "64",
  "65",
];

export const cou = ["India","pakistan"]